services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: smart-tasks-php:dev
        container_name: smart-tasks-app
        restart: unless-stopped
        environment:
            APP_ENV: local
            APP_DEBUG: "true"
            APP_URL: http://localhost:8000
            LOG_CHANNEL: daily
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: smart_task_api
            DB_USERNAME: laravel
            DB_PASSWORD: laravel
            REDIS_HOST: redis
            REDIS_PORT: 6379
            QUEUE_CONNECTION: redis
            CACHE_DRIVER: redis
            SESSION_DRIVER: redis
        volumes:
            - ./:/var/www/html:cached
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:1.27-alpine
        container_name: smart-tasks-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    db:
        image: mysql:8.4
        container_name: smart-tasks-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: smart_task_api
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: root
#        command: ["--default-authentication-plugin=mysql_native_password"]
#        ports: ["3306:3306"]
        volumes:
            - mysqldata:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "laravel", "-plaravel"]
            interval: 5s
            timeout: 5s
            retries: 20

    redis:
        image: redis:7-alpine
        container_name: smart-tasks-redis
        restart: unless-stopped
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redisdata:/data

volumes:
    mysqldata:
    redisdata:
